version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    depends_on:
      - db
    build:
      context: .
    container_name: app
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/taxes
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports: 
      - 8080:8080

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=taxes
