# Tell Spring where to get the data from
spring:
    datasource:
        url: jdbc:postgresql://group-4-db.cluster-c4eqo06kg56i.us-east-1.rds.amazonaws.com:5432/taxes
        username: postgres
        password: postgres                              

    output:
        ansi:
            enabled: ALWAYS

    jpa:
        hibernate:
            ddl-auto: update
