# Tell Spring where to get the data from
spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/taxes
        username: postgres
        password: root                                 

    output:
        ansi:
            enabled: ALWAYS

    jpa:
        hibernate:
            ddl-auto: update
